# Generated by Django 4.2.7 on 2023-11-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
