# Generated by Django 4.2.7 on 2023-11-25 21:59

import Profile.helper
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AA', 'Associate of Arts'), ('AS', 'Associate of Science'), ('BA', 'Bachelor of Arts'), ('BSc', 'Bachelor of Science'), ('BFA', 'Bachelor of Fine Arts'), ('LLB', 'Bachelor of Laws'), ('LLM', 'Master of Laws'), ('JD', 'Juris Doctor'), ('BCL', 'Bachelor of Civil Law'), ('BLS', 'Bachelor of Legal Studies'), ('BPhil', 'Bachelor of Philosophy'), ('BEng', 'Bachelor of Engineering'), ('BEd', 'Bachelor of Education'), ('MA', 'Master of Arts'), ('MSc', 'Master of Science'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy'), ('EdD', 'Doctor of Education'), ('MD', 'Doctor of Medicine'), ('EdS', 'Education Specialist'), ('EngD', 'Doctor of Engineering'), ('PsyD', 'Doctor of Psychology'), ('DMA', 'Doctor of Musical Arts')], max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField(max_length=4, validators=[django.core.validators.MaxValueValidator(2023)])),
                ('transcript', models.FileField(blank=True, null=True, upload_to=Profile.helper.transcript_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
