# Generated by Django 4.2.7 on 2023-11-26 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='graduation_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
