# Generated by Django 4.2.7 on 2023-11-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_degree_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
