# Generated by Django 4.2.7 on 2023-11-26 16:44

import Profile.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0003_degree_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_link', models.CharField(blank=True, max_length=100, null=True)),
                ('sample', models.FileField(blank=True, null=True, upload_to=Profile.helper.sample_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
