# Generated by Django 4.2.7 on 2023-11-29 02:45

import Profile.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_useraccount_mobile_number'),
        ('Profile', '0006_degree_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('study_area', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAssistant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=Profile.helper.profile_picture_upload_path)),
                ('linkedin_url', models.CharField(blank=True, max_length=250, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to=Profile.helper.cv_upload_path)),
                ('interests', models.ManyToManyField(blank=True, null=True, to='Profile.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=Profile.helper.profile_picture_upload_path)),
                ('department', models.CharField(blank=True, choices=[('Humanities & Social Sciences', 'Humanities & Social Sciences'), ('Business Administration', 'Business Administration'), ('Computer Science & Information Systems', 'Computer Science & Information Systems'), ('Engineering', 'Engineering')], max_length=100, null=True)),
                ('interests', models.ManyToManyField(blank=True, null=True, to='Profile.interest')),
            ],
        ),
    ]
