# Generated by Django 4.2.7 on 2023-11-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_interest_researchassistant_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='interests',
            field=models.ManyToManyField(blank=True, to='Profile.interest'),
        ),
        migrations.AlterField(
            model_name='researchassistant',
            name='interests',
            field=models.ManyToManyField(blank=True, to='Profile.interest'),
        ),
    ]
