# Generated by Django 4.2.7 on 2024-02-11 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('todo', 'To Do'), ('in_review', 'In Review'), ('done', 'Done'), ('completed', 'Completed'), ('annulled', 'Annulled')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=20)),
                ('estimated_project_hours', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('todo', 'To Do'), ('in_review', 'In Review'), ('done', 'Done'), ('completed', 'Completed'), ('annulled', 'Annulled')], default='todo', max_length=20)),
                ('hours_required', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectmilestone')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projecttask')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reviewer', to=settings.AUTH_USER_MODEL)),
                ('target_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStudyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_area', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Algorithm', 'Algorithm'), ('Computer Engineering', 'Computer Engineering'), ('Cryptography', 'Cryptography'), ('Robotics', 'Robotics'), ('Computer Vision', 'Computer Vision'), ('Software Engineering', 'Software Engineering'), ('Computational Science', 'Computational Science'), ('Numerical Analysis', 'Numerical Analysis'), ('Market Research', 'Market Research'), ('Financial Accounting', 'Financial Accounting'), ('International Trade & Policy', 'International Trade & Policy'), ('Organizational Behavior', 'Organizational Behavior'), ('Managerial Behavior', 'Managerial Behavior'), ('Marketing', 'Marketing'), ('Operations Management', 'Operations Management'), ('International Finance', 'International Finance'), ('Supply-Chain Management', 'Supply-Chain Management'), ('Business Law', 'Business Law'), ('Competitive Strategy', 'Competitive Strategy'), ('Corporate Finance', 'Corporate Finance'), ('Product Development', 'Product Development')], max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
        migrations.AddField(
            model_name='projectrole',
            name='team_member_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.teammemberrole'),
        ),
        migrations.CreateModel(
            name='ProjectMatchScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlindProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('intended_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intended_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
