# Generated by Django 4.2.7 on 2023-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscelleneous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
